### ISSUE TITLE
TypeError in simple_text_classfication tutorial

### ISSUE THREAD

**Issue by megaSpoon** [intel-analytics/BigDL#1330]
In the [simple_text_classfication](https://github.com/intel-analytics/BigDL/blob/branch-0.1/pyspark/example/tutorial/simple_text_classification/text_classfication.ipynb), the link "BigDL python text classfication example" is broken. The notebook was tested in the following Env:
**python 2.7
spark 1.6.3
bigdl0.2.0**(use the nightly build with _spark1.6.3_)

Found this error in the **10th** cell related to the optimizer part.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-a2f775a126b6> in <module>()
     37 print('Start to train the model')
     38 #configure optimizer
---> 39 optimizer,train_summary,val_summary = create_optimizer(model,'adagrad-'+ dt.datetime.now().strftime("%Y%m%d-%H%M%S"))
     40 trained_model = optimizer.optimize()
     41 print("Optimization Done.")

<ipython-input-10-a2f775a126b6> in create_optimizer(model, app_name, logdir, batch_size, lr, lrd, optim, val, max_epoch)
     20         batch_size=batch_size,
     21         optim_method=optim,
---> 22         state=state)
     23 
     24     optimizer.set_validation(

TypeError: __init__() got an unexpected keyword argument 'state'

Also tested with _spark2.1_, but failed at init_engine().

**Comment by megaSpoon** [comment]
fix this issue by making a few changes inspired from codes [here](https://github.com/intel-analytics/BigDL/blob/master/pyspark/bigdl/models/textclassifier/textclassifier.py): 
1. delete the state
2. modify the parameters: optim, val
```python
def create_optimizer(model,
                     app_name,
                     logdir='/tmp/bigdl_summaries',
                     batch_size=batch_size,
                     lr=0.01,
                     lrd=0.0002,
                     optim=Adagrad,
                     val=[Top1Accuracy()],
                     max_epoch=2):
    print("optimize summary will be write to :",logdir+'/'+app_name)

    #configure optimizer
    optimizer = Optimizer(
        model=model,
        training_rdd=train_rdd,
        criterion=ClassNLLCriterion(),
        end_trigger=MaxEpoch(max_epoch),
        batch_size=batch_size,
        optim_method=optim(learningrate=0.01, learningrate_decay=0.0002))
    
    optimizer.set_validation(
        batch_size=batch_size,
        val_rdd=val_rdd,
        trigger=EveryEpoch(),
        val_method=val
    )
    train_summary = TrainSummary(log_dir=logdir, app_name=app_name)
    train_summary.set_summary_trigger("Parameters", SeveralIteration(50))
    val_summary = ValidationSummary(log_dir=logdir, app_name=app_name)
    optimizer.set_train_summary(train_summary)
    optimizer.set_val_summary(val_summary)
    return optimizer,train_summary,val_summary

print('Start to train the model')
#configure optimizer
optimizer,train_summary,val_summary = create_optimizer(model,'adagrad-'+ dt.datetime.now().strftime("%Y%m%d-%H%M%S"))
trained_model = optimizer.optimize()
print("Optimization Done.")
```
But found another error in the 13rd cell, shown below:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-c31d5c5428f4> in <module>()
      3 # each event data has 3-dimension value, in the form of (iteration_count, value, timestamp)
      4 plt.plot(loss_adagrad[:,0],loss_adagrad[:,1],label='train')
----> 5 plt.plot(valloss_adagrad[:,0],valloss_adagrad[:,1],label='val',color='green')
      6 plt.scatter(valloss_adagrad[:,0],valloss_adagrad[:,1],color='green')
      7 plt.legend();

IndexError: too many indices for array

---------------------------------------------------------------------------

**Comment by megaSpoon** [comment]
Just found the cause of this error is that there is no element in the val_summary array.

**Comment by qiuxin2012** [comment]
Have you assigned a value for `val`? It looks you are deliverying a `null` value to `val_method`
You need to change from
```
optimizer.set_validation(
        batch_size=batch_size,
        val_rdd=val_rdd,
        trigger=EveryEpoch(),
        val_method=val
    )
```
to
```python
optimizer.set_validation(
        batch_size=batch_size,
        val_rdd=val_rdd,
        trigger=EveryEpoch(),
        val_method=[Top1Accuracy()]
    )
```

**Comment by megaSpoon** [comment]
I set val from the parameter list in the create_optimizer method.

def create_optimizer(model,
                     app_name,
                     logdir='/tmp/bigdl_summaries',
                     batch_size=batch_size,
                     lr=0.01,
                     lrd=0.0002,
                     optim=Adagrad,
                     val=[Top1Accuracy()],
                     max_epoch=2):

**Comment by megaSpoon** [comment]
Isuue fixed. should change `val=[Top1Accuracy()]` into `val=[Top1Accuracy(), loss()]` to activate the loss logging.

Here is the changed code for the create_optimizer part:

```python
def create_optimizer(model,
                     app_name,
                     logdir='/tmp/bigdl_summaries',
                     batch_size=batch_size,
                     lr=0.01,
                     lrd=0.0002,
                     optim=Adagrad,
                     val=[Top1Accuracy(), loss()],
                     max_epoch=2):
    print("optimize summary will be write to :",logdir+'/'+app_name)

    #configure optimizer
    optimizer = Optimizer(
        model=model,
        training_rdd=train_rdd,
        criterion=ClassNLLCriterion(),
        end_trigger=MaxEpoch(max_epoch),
        batch_size=batch_size,
        optim_method=optim(learningrate=lr, learningrate_decay=lrd))
    
    optimizer.set_validation(
        batch_size=batch_size,
        val_rdd=val_rdd,
        trigger=EveryEpoch(),
        val_method=val
    )
    train_summary = TrainSummary(log_dir=logdir, app_name=app_name)
    train_summary.set_summary_trigger("Parameters", SeveralIteration(50))
    val_summary = ValidationSummary(log_dir=logdir, app_name=app_name)
    optimizer.set_train_summary(train_summary)
    optimizer.set_val_summary(val_summary)
    return optimizer,train_summary,val_summary

print('Start to train the model')
#configure optimizer
optimizer,train_summary,val_summary = create_optimizer(model,'adagrad-'+ dt.datetime.now().strftime("%Y%m%d-%H%M%S"))
trained_model = optimizer.optimize()
print("Optimization Done.")
```

**Comment by megaSpoon** [comment]
Fixed with spark 2.1. My original start_notebook.sh for spark2.1 set the BigDL home incorrectly with a typo wich gives arise to the TypeError: 'JavaPackage' object is not callable. Now it runs perfectly within the anaconda2 virtual env. This issue can be closed now. @jason-dai
