### ISSUE TITLE
Facing issue when install this library : "python3.9 -m pip install --ignore-installed PyYAML --pre --upgrade bigdl-chronos[pytorch]==2.4.0"

### ISSUE THREAD

**Issue by SjeYinTeoIntel** [intel-analytics/BigDL#10512]
![image](https://github.com/intel-analytics/BigDL/assets/78522263/efafdcec-8071-405d-a7a4-a343ec07cbb7)

We are trying to install this library. 
> python3.9 -m pip install --ignore-installed PyYAML --pre --upgrade bigdl-chronos[pytorch]==2.4.0
but seeing issue above when install this library. 
It is working previously.
We are using bigdlspark==2.4.0 version. Without above library, will causing this error:
ImportError: cannot import name 'TCNForecaster' from 'bigdl.chronos.forecaster' (/usr/local/lib/python3.9/dist-packages/bigdl/chronos/forecaster/__init__.py)
Is this library no longer exist?

**Comment by plusbang** [comment]
I could not reproduce this installation error when I directly run `python3.9 -m pip install --ignore-installed PyYAML --pre --upgrade bigdl-chronos[pytorch]==2.4.0`. But this error seems to be caused by `numpy` version. **You could try `python3.9 -m pip install --ignore-installed PyYAML bigdl-chronos[pytorch]==2.4.0` instead.**

**Comment by SjeYinTeoIntel** [comment]
Hi,
Thanks for it.
it works with python3.9 -m pip install --ignore-installed PyYAML bigdl-chronos[pytorch]==2.4.0.
